
package ma.emsi.dhissiayman;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "EtudiantWService", targetNamespace = "http://Service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EtudiantWService {


    /**
     * 
     * @return
     *     returns java.util.List<ma.emsi.dhissiayman.Eleve>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listStudents", targetNamespace = "http://Service/", className = "ma.emsi.dhissiayman.ListStudents")
    @ResponseWrapper(localName = "listStudentsResponse", targetNamespace = "http://Service/", className = "ma.emsi.dhissiayman.ListStudentsResponse")
    @Action(input = "http://Service/EtudiantWService/listStudentsRequest", output = "http://Service/EtudiantWService/listStudentsResponse")
    public List<Eleve> listStudents();

}
